export interface Fruit {
  id: string,
  name: string,
  vote: string,
}

export const rankData1: Array<Fruit> = [
  {id: '1', name: '苹果', vote: '12080'},
  {id: '2', name: '苹果', vote: '10320'},
  {id: '3', name: '苹果', vote: '9801'},
  {id: '4', name: '苹果', vote: '8431'},
  {id: '5', name: '苹果', vote: '7546'},
  {id: '6', name: '苹果', vote: '7431'},
  {id: '7', name: '苹果', vote: '7176'},
  {id: '8', name: '苹果', vote: '7003'},
  {id: '9', name: '苹果', vote: '3982'},
  {id: '10', name: '苹果', vote: '6742'},
]
export const rankData2: Array<Fruit> = [
  {id: '11', name: '苹果', vote: '6653'},
  {id: '12', name: '苹果', vote: '6523'},
  {id: '13', name: '苹果', vote: '6423'},
  {id: '14', name: '苹果', vote: '6345'},
  {id: '15', name: '苹果', vote: '6245'},
  {id: '16', name: '苹果', vote: '6157'},
  {id: '17', name: '苹果', vote: '6023'},
  {id: '18', name: '苹果', vote: '5967'},
  {id: '19', name: '苹果', vote: '5864'},
  {id: '20', name: '苹果', vote: '5011'},
]